name: how_to_cook_parser
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  isar: ^2.5.0
  path: ^1.8.1
  yaml: ^3.1.0
  markdown: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.8
  isar_flutter_libs: ^2.5.0
  isar_generator: ^2.5.0
  lints: ^1.0.0
